version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: ./backend
    links: 
      - db
      # volumes:
        #   - ./backend:/app/backend
    ports:
      - "3001:3001"
    command: "bundle exec rails server -p 3001 -b 0.0.0.0"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        API_URL: http://0.0.0.0:3001
    # volumes:
    #   - ./frontend:/app/frontend
    volumes: 
      - build_folder:/frontend/build


  nginx:
    image: nginx:latest
    ports:
      - 3000:3000
    volumes: 
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on: 
      - backend
      - frontend
  
volumes: 
  build_folder:
