version: "3.7"

services:
  db:
    image: postgres
    volumes:
        - ./tmp/db:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: password
  ruby_dev:
    build: .
    links: 
      - db
    container_name: ruby_container
    ports:
      - "3001:3001"
    volumes:
        - ../backend:/app/backend
    depends_on: 
      - db